---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-admin
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.admin.username | quote }}
  email: {{ .Values.admin.email | quote }}
  password: {{ include "gitea.adminPassword" . | quote }}
