apiVersion: v1
kind: Namespace
metadata:
  name: homestack-k8up

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: homestack-k8up
spec:
  chart:
    spec:
      chart: k8up
      version: "4.8.5"
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true