apiVersion: v1
kind: Namespace
metadata:
  name: k8up

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  chart:
    spec:
      chart: k8up
      version: "1.5.0"
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    # настройте backup schedules, s3 creds и т.д.
    backup:
      enabled: true
    restore:
      enabled: true
    prune:
      enabled: true