# clusters/default/kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../components/core
  - ../../components/apps/backup-server
  - ../../components/apps/vaultwarden