apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  chart:
    spec:
      chart: crossplane
      version: "2.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    function:
      packages:
        - xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.11.0
        - xpkg.upbound.io/crossplane-contrib/function-auto-ready:v0.5.0