apiVersion: v1
kind: Namespace
metadata:
  name: homystack-ingress-nginx

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: homystack-ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "4.8.3"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    controller:
      service:
        type: LoadBalancer
      ingressClassResource:
        name: nginx
        enabled: true
        default: true