---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: homy-stack-gitea
  namespace: cozy-public
spec:
  interval: 5m
  chart: ./packages/apps/gitea
  sourceRef:
    kind: GitRepository
    name: homy-stack
  reconcileStrategy: Revision
