apiVersion: v1
kind: Namespace
metadata:
  name: homystack-headlamp

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace:  homystack-headlamp
spec:
  chart:
    spec:
      chart: headlamp
      version: "0.20.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: headlamp.local
          paths:
            - path: /
              type: Prefix
