apiVersion: v1
kind: Namespace
metadata:
  name: homystack-headlamp

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace:  homystack-headlamp
spec:
  chart:
    spec:
      chart: headlamp
      version: "0.35.0"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  interval: 10m
  install:
    createNamespace: true
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: headlamp.local
          paths:
            - path: /
              type: Prefix
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp-nodeport
  namespace: homystack-headlamp
  labels:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/name: headlamp
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30880  
      protocol: TCP
  selector:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/name: headlamp